package com.learnershi.rclasssocket.entity.enums


/**
 * MessageType Enum
 *
 */
enum class MessageType {
    // test
    GREET,  // 연결 확인

    // ClassRoom
    CONNECT,
    CLASS_CHANGE,
    STUDENT_CONNECT,
    STUDENT_DISCONNECT,
    DISCONNECT,
    QUIZ_START,
    QUIZ_SUBMIT,
    STUDY_MODE,
    STUDY_ACTION,
    QUIZ_RESULT,
    QUIZ_ANSWER,
    HANDS_UP,
    RANDOM_PICK,
    MINI_WINDOW,
    MINI_WINDOW_CURRENT,
    MINI_WINDOW_CLOSE,
    SYNC_CLASSROOM,
    SYNC,
    SPEED_QUIZ_START,
    SPEED_QUIZ_SUBMIT,
    DRAW_PATH,
    VIRTUAL_TOOLS,
    VIRTUAL_TOOL_ANIMATIONS,
    SPOTLIGHT,
    SPOTLIGHT_CLOSE,
    CREATE_CLASS_GOAL,
    UPDATE_CLASS_GOAL,
    DELETE_CLASS_GOAL,
    MEMO,
    REVEAL,
    REVEAL_DELETED,
    COMPREHENSION_QUESTION,
    COMPREHENSION_ANSWER,
    MEDIA,
    READ,
    BADGE,
    ERROR,



}