package com.learnershi.rclasssocket.entity.enums


/**
 * MessageType Enum
 *
 */
enum class MessageType {
    // test
    GREET,  // 연결 확인

    // ClassRoom
    CONNECT,
    CLASS_CHANGE,
    DISCONNECT,

    QUIZ,
    QUIZ_SUBMIT,
    QUIZ_RESULT,
    QUIZ_RESULT_HIDE,
    QUIZ_RESULT_VIEW,
    QUIZ_ANSWER,
    QUIZ_ANSWER_HIDE,
    HANDS_UP,
    HANDS_UP_SUBMIT,
    HANDS_UP_RESULT,
    RANDOM_PICK,
    RANDOM_PICK_RESULT,
    VIRTUAL_TOOLS,
    VIRTUAL_TOOL_ANIMATIONS,
    MINI_WINDOW,
    MINI_WINDOW_CURRENT,
    MINI_WINDOW_CLOSE,
    SPEED_QUIZ,
    SPEED_QUIZ_SUBMIT,
    SPOTLIGHT,
    SPOTLIGHT_SUBMIT,
    SPOTLIGHT_CLOSE,
    SCREENSHOT,
    SCREENSHOT_SUBMIT,
    MEDIA,
    READ,
    READ_SUBMIT,
    TAB_ADD,
    TEXTBOOK_CHANGE,
    DRAW_RESET,

    CLASS_GOAL,
    MEMO,
    REVEAL,
    COMPREHENSION_QUESTION,
    COMPREHENSION_ANSWER,
    BADGE,
    STUDY_DATA,
    ERROR,



}